In [1]:
import torch

In [2]:
torch.__version__

'2.2.2+cpu'

In [3]:
torch.Tensor([1,2])


tensor([1., 2.])

In [5]:
torch.tensor([1.1,2])

tensor([1.1000, 2.0000])

In [6]:
t = torch.tensor([1,2])
t.dtype

torch.int64

In [7]:
import numpy as np
a = np.array([1,2])
t = torch.tensor(a)
t.dtype

torch.int32

In [10]:
a = torch.tensor([1.1, 2.2], dtype=torch.int16)
a.dtype

C:\Users\Administrator\AppData\Local\Temp\ipykernel_564\1533875204.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  a = torch.tensor([1.1, 2.2], dtype=torch.int16)


torch.int16

In [14]:
t=torch.tensor([1,2])
t.float().dtype

torch.float32

In [15]:
t.double().dtype

torch.float64

In [18]:
t=torch.tensor([1,2])
# 张量维度
t.ndim

1

In [20]:
t=torch.tensor([[1,2],[1,2]])
# 张量维度
t.ndim

2

In [21]:
t.numel()


4

In [23]:
t.reshape((1,4,1))

tensor([[[1],
         [2],
         [1],
         [2]]])

In [25]:
t.reshape(1,4,1).flatten()

tensor([1, 2, 1, 2])

In [26]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [31]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [32]:
torch.diag(torch.tensor([1,2,2,3]))


tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 2, 0],
        [0, 0, 0, 3]])

In [33]:
torch.rand([2,3])

tensor([[0.1369, 0.5552, 0.3219],
        [0.1051, 0.5612, 0.8302]])

In [35]:
torch.randn([2,3])

tensor([[-0.5354,  2.2641,  0.6878],
        [ 0.9479, -1.0431, -1.8918]])

In [37]:
torch.randint(1,10,[2,3])

tensor([[3, 1, 5],
        [2, 5, 6]])

In [45]:
torch.linspace(1,10,5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [47]:
torch.empty([2,3])


tensor([[-2.6671e+13,  8.3938e-43,  1.4013e-45],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00]])

In [48]:
torch.full([2,3],9)

tensor([[9, 9, 9],
        [9, 9, 9]])

In [49]:
t1 = torch.empty([2,3])
t = t1.clone()


In [50]:
t


tensor([[-2.6670e+13,  8.3938e-43,  2.0000e+00],
        [ 2.5000e+00,  3.0000e+00,  3.5000e+00]])