In [15]:
import torch

In [22]:
torch.random.manual_seed(420)
model = torch.nn.Linear(2,1)

In [28]:
X = torch.Tensor([[0,0],[0,1],[1,0],[1,1]])
X

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

In [24]:
zhat = model(X)

In [25]:
zhat

tensor([[0.6730],
        [0.2473],
        [1.1048],
        [0.6792]], grad_fn=<AddmmBackward0>)

In [26]:
model.weight

Parameter containing:
tensor([[ 0.4318, -0.4256]], requires_grad=True)

In [27]:
model.bias

Parameter containing:
tensor([0.6730], requires_grad=True)