In [1]:
import torch
from torch.nn import functional as F

In [44]:
class Model(torch.nn.Module):
    def __init__(self, in_feature=20,out_feature=3):
        """
        in_feature: 输入层神经元个数
        out_feature: 输出层神经元个数
        """
        super().__init__()
        self.linear1 = torch.nn.Linear(in_feature,13,bias=True)
        self.linear2 = torch.nn.Linear(13,8,bias=True)
        self.output = torch.nn.Linear(8,out_feature,bias=True)
        

    def forward(self,X):
        z1 = self.linear1(X)
        sigma1 = F.relu(z1)
        z2 = self.linear2(sigma1)
        sigma2 = F.sigmoid(z2)
        output = self.output(sigma2)
        sigma3 = F.softmax(output,dim=1)
        return sigma3
        

In [45]:
torch.random.manual_seed(420)
X = torch.rand([500,20],dtype=torch.float32)
y = torch.randint(0,3,[500,1],dtype=torch.float32)

In [46]:
y.unique()

tensor([0., 1., 2.])

In [49]:
torch.random.manual_seed(420)
net = Model(in_feature=20,out_feature=3)
net.forward(X)

tensor([[0.4140, 0.3496, 0.2365],
        [0.4210, 0.3454, 0.2336],
        [0.4011, 0.3635, 0.2355],
        ...,
        [0.4196, 0.3452, 0.2352],
        [0.4153, 0.3455, 0.2392],
        [0.4153, 0.3442, 0.2405]], grad_fn=<SoftmaxBackward0>)

tensor([[0.4140, 0.3496, 0.2365],
        [0.4210, 0.3454, 0.2336],
        [0.4011, 0.3635, 0.2355],
        ...,
        [0.4196, 0.3452, 0.2352],
        [0.4153, 0.3455, 0.2392],
        [0.4153, 0.3442, 0.2405]], grad_fn=<SoftmaxBackward0>)

In [52]:
net.linear1.weight.size()

torch.Size([13, 20])

In [53]:
net.linear1.bias.size()

torch.Size([13])

In [54]:
net.training # 是否用于训练

True

In [56]:
#net.cuda() # 将整个网络转移到GPU上
net.cpu() # 将整个网络转移到CPU上

Model(
  (linear1): Linear(in_features=20, out_features=13, bias=True)
  (linear2): Linear(in_features=13, out_features=8, bias=True)
  (output): Linear(in_features=8, out_features=3, bias=True)
)

In [59]:
net.parameters() # 全部参数

<generator object Module.parameters at 0x000000002F7D0430>